### ISSUE TITLE
Fanshim Service Conflict

### ISSUE THREAD

**Issue by Steveyboykidd** [pimoroni/fanshim-python#30]
I am using an RPI 4 with Buster and everything is up to date.
I have installed the fanshim and installed the fanshim service according to the instructions and 
it works perfectly.

Now I have installed the AlexaPi  from https://github.com/alexa-pi/AlexaPi/wiki/Installation
and that is also working perfectly.

There is some kind of clash with the fanshim service.
As soon as the AlexaPi service starts either at reboot or with sudo systemctl status AlexaPi.service  then my fanshim service is messed up and fan is always on.  I check fanshim service status and it is running active.
If now I restart fanshim service then both fanshim and AlexaPi service are working fine until next reboot.

**Comment by Gadgetoid** [comment]
Presumably because AlexaPi uses a bunch of GPIO for various features, and your settings conflict with the pins used by Fan SHIM - https://github.com/alexa-pi/AlexaPi/blob/c8adfbe3f7e09b40c7d03be0e6925be88b7cbe61/src/config.template.yaml#L118-L124

Restarting Fan SHIM would switch the GPIO back to whatever it needs.
